import Head from 'next/head'
import { Box, Button, Flex, FormControl, FormLabel, Heading, Input, Modal, ModalBody, ModalCloseButton, ModalContent, ModalFooter, ModalHeader, ModalOverlay, Text, useDisclosure, VStack } from "@chakra-ui/react"
import React from 'react'
import { EditIcon, DeleteIcon } from '@chakra-ui/icons'

const Feature = ({ title, desc, ...rest }) => {
  return (
    <Box p={5}  borderWidth='1px' {...rest}>
      <Flex className='positioning'>
        <Heading fontSize='xl'>{title}</Heading>
        <div>
          <Button colorScheme='yellow'><EditIcon/></Button>
          <Button colorScheme='red'  ml='2'><DeleteIcon/></Button>
        </div>
      </Flex>
      
      <Text mt={2}>{desc}</Text>
    </Box>
  )
}

export default function Home() {

  const { isOpen, onOpen, onClose } = useDisclosure()

  const initialRef = React.useRef(null)
  const finalRef = React.useRef(null)

  return (
    <div className='main-background'>
      <Head>
        <title>Todo Example - Monago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className='flex-center'>
        <nav className='navigation-menu'>
          <div className='logo-main'>
            <a>Todo</a>
          </div>
          <div>
            <Button colorScheme='orange' onClick={onOpen}>Add Task</Button>
          </div>
        </nav>
        <div className='container'>
        <Heading fontSize='xl' mb={5}>Todo List</Heading>
        <VStack spacing={8}>
          <Feature
            title='Plan Money'
            desc='The future can be even brighter but a goal without a plan is just a wish'
          />
          <Feature
            title='Save Money'
            desc='You deserve good things. With a whooping 10-15% interest rate per annum, grow your savings on your own terms with our completely automated process'
          />
        </VStack>
        </div>
      </Box>
        <Modal
          initialFocusRef={initialRef}
          finalFocusRef={finalRef}
          isOpen={isOpen}
          onClose={onClose}
        >
        <ModalOverlay />
          <ModalContent>
            <ModalHeader>Activity</ModalHeader>
            <ModalCloseButton />
            <ModalBody pb={6}>
              <FormControl>
                <FormLabel>Name Activity</FormLabel>
                <Input ref={initialRef} placeholder='Name' />
              </FormControl>

              <FormControl mt={4}>
                <FormLabel>Description Activity</FormLabel>
                <Input placeholder='Description' />
              </FormControl>
            </ModalBody>

            <ModalFooter>
              <Button colorScheme='blue' mr={3}>
                Save
              </Button>
              <Button onClick={onClose}>Cancel</Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
    </div>
    
  )
}
